version: "3.9"

services:
  web:
    build:
      context: ..
      dockerfile: web/Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Data Source=/app/web.db
    volumes:
      - ../web/web.db:/app/web.db
  frontend:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    container_name: frontend
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - Backend=http://backend:8080/api/v1/
